export const LIST_VOLUME_FIELD = [
  "best10BidVol",
  "best9BidVol",
  "best8BidVol",
  "best7BidVol",
  "best6BidVol",
  "best5BidVol",
  "best4BidVol",
  "best3BidVol",
  "best2BidVol",
  "best1BidVol",
  "matchedVolume",
  "best1OfferVol",
  "best2OfferVol",
  "best3OfferVol",
  "best4OfferVol",
  "best5OfferVol",
  "best10OfferVol",
  "best10OfferVol",
  "best10OfferVol",
  "best10OfferVol",
  "best10OfferVol",
  "nmTotalTradedQty",
  "currentBidQty",
  "currentOfferQty",
  "buyForeignQtty",
  "sellForeignQtty",
  "remainForeignQtty",
];

export const LIST_VALUE_FIELD = ["buyForeignValue", "sellForeignValue"];
